# travis.yml
language: node_js
node_js:
  - '8'
install:
  - yarn
script:
  - yarn run commitlint
  - yarn run lint
  - yarn run format
deploy:
  # https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  on:
    branch: master
