# travis.yml
language: node_js
node_js:
  - '8'
install:
  - yarn
script:
  - yarn run commitlint
  - yarn run lint
  - yarn run format
  - yarn build
deploy:
  # https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: public
  verbose: true
  keep_history: false
  fqdn: thibaultfriedrich.io
  on:
    branch: master
notifications:
  slack: 
    rooms:
      - secure: secure: "fhdmkgj9z0srPTPeBzfCwEpiznww9HBUadfbgHZ5LB1rCrXKXZQwdiWGgcSds306zC9FsND2986A7SUB8hnUVbB8BZLaUPLvZBok7S7eWKYxDBjh8BrlnKOE4EkKOyKRTxZ31Nh0sOpbNJBlvNlM6bY6NvzGuWXe9RTaPCTDuewtC8QlEVqQCejVAgJWXkN33h94sGPWwQttwiidMNgkSLWcOvQSk94O471QIsDtOA5M1lmllsXb6BD6wELaMHoHV9t9+iNvmdi21/bnBLFqpvtRzKrcZWiQI7uI2f7rzvXFLxv/CvYXPt5EKmv9rXBvPju87nJS47R3CA13Ujtt1cnJSGCpvfKKad8816UYU6LjCzdOy129+7bSs04kHW5wdhXbElthoTPoDe9kBJS37B0GqDKyva3KNWt/VR4XFwboKXlATV0jp2gaRAbRX6IRXrqHvYohQibDPlyEU34TUBzKNOWyI8W8AqDOclhzrLF1ATw13oNGs/Vtgv9Cqk2SjyKmShcwZe+iCXzpmfzGjskhVn7KcJZdoGM2016e3dk+cKVGfsej19+cAErb17tYbJHFmvE6qalOZGJ0nBYsj8lbqbzD2ywLVa74Hc7wOUzGcyxeehN5ePxNqVIFCP1zE3ObvRrPtf3EqsANaunanh8Nho1u0gihFU5Ayox/hWc="
    on_success: always # change: send a notification when the build status changes.
    on_failure: always # always: always send a notification.
